#FROM pytorch/pytorch:1.1.0-cuda10.0-cudnn7.5-runtime

FROM ubuntu:20.04
RUN apt-get update
FROM continuumio/miniconda3
WORKDIR /workspace
COPY ./ ./

# SET BASH AS CURRENT SHELL
RUN chsh -s /bin/bash
SHELL ["/bin/bash", "-c"]




RUN conda update conda 
RUN conda env create -f pillar_linux.yml

#RUN echo "conda activate pillar" >> ~/.bashrc
#ENV PATH /opt/conda/envs/pillar/bin:$PATH
#ENV CONDA_DEFAULT_ENV $pillar

#COPY . .
#CMD [ "python", "-u", "train.py" ]